# Generated by Django 4.2.3 on 2023-07-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('BIO', 'Biography'), ('FIC', 'Fiction'), ('HIS', 'History'), ('HOR', 'Horror'), ('MYS', 'Mystery'), ('NOF', 'NonFiction'), ('ROM', 'Romance'), ('SCI', 'SciFi'), ('THR', 'Thriller')], max_length=5)),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('cover', models.ImageField(upload_to='book')),
                ('edition', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('publication_year', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('minimum_threshold', models.IntegerField()),
                ('buying_price', models.FloatField()),
                ('selling_price', models.FloatField()),
            ],
        ),
    ]
