# Generated by Django 4.0 on 2023-07-11 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_promotions_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Promotions',
            new_name='Promotion',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
