# Generated by Django 4.0 on 2023-07-18 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_user_managers_user_activation_token'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
