# Generated by Django 4.0 on 2023-07-18 06:18

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(default=app.models.random_number_generator, unique=True),
        ),
    ]
