# Generated by Django 4.0 on 2023-07-18 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='account_id',
        ),
    ]
