# Generated by Django 4.0 on 2023-07-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
