# Generated by Django 4.0 on 2023-07-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_loggedin',
            field=models.BooleanField(default=False),
        ),
    ]
