# Generated by Django 4.0 on 2023-07-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apartment_suite',
            field=models.CharField(blank=True, default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='card_number',
            field=models.CharField(default=' ', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_email',
            field=models.CharField(blank=True, default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_phone',
            field=models.CharField(blank=True, default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='expiration_date',
            field=models.CharField(blank=True, default=' ', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_code',
            field=models.CharField(blank=True, default=' ', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='street_address',
            field=models.CharField(blank=True, default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='zip_code',
            field=models.CharField(blank=True, default=' ', max_length=30),
        ),
    ]
