# Generated by Django 4.2.3 on 2023-07-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_book_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='topSeller',
            field=models.BooleanField(default=False),
        ),
    ]
